# Generated by Django 4.1.7 on 2023-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_place', models.IntegerField()),
                ('lugarcam', models.CharField(max_length=50)),
                ('num_cam_lug', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomlugar', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('num', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fec_cre', models.DateTimeField(auto_now_add=True)),
                ('fec_mod', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_place', models.IntegerField()),
                ('id_cam', models.IntegerField()),
                ('personas', models.IntegerField()),
                ('tmstmp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
