# Generated by Django 4.1.7 on 2023-04-20 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aforoReg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='tmstmp',
        ),
        migrations.AddField(
            model_name='register',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha en formato Y-M-D', verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='register',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Hora en formato HH:MM:SS', verbose_name='Hora'),
        ),
    ]
